In [62]:
# data read -> no null, no dup -> hypothesis -> chi and anova -> encoding -> feature scaling -> sampling

In [63]:
import pandas as pd

In [64]:
df = pd.read_csv('heart_attack_prediction_dataset.csv')

In [65]:
df

,Patient ID,Age,Sex,Cholesterol,Blood Pressure,Heart Rate,Diabetes,Family History,Smoking,Obesity,...,Sedentary Hours Per Day,Income,BMI,Triglycerides,Physical Activity Days Per Week,Sleep Hours Per Day,Country,Continent,Hemisphere,Heart Attack Risk
0,BMW7812,67,Male,208,158/88,72,0,0,1,0,...,6.615001,261404,31.251233,286,0,6,Argentina,South America,Southern Hemisphere,0
1,CZE1114,21,Male,389,165/93,98,1,1,1,1,...,4.963459,285768,27.194973,235,1,7,Canada,North America,Northern Hemisphere,0
2,BNI9906,21,Female,324,174/99,72,1,0,0,0,...,9.463426,235282,28.176571,587,4,4,France,Europe,Northern Hemisphere,0
3,JLN3497,84,Male,383,163/100,73,1,1,1,0,...,7.648981,125640,36.464704,378,3,4,Canada,North America,Northern Hemisphere,0
4,GFO8847,66,Male,318,91/88,93,1,1,1,1,...,1.514821,160555,21.809144,231,1,5,Thailand,Asia,Northern Hemisphere,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8758,MSV9918,60,Male,121,94/76,61,1,1,1,0,...,10.806373,235420,19.655895,67,7,7,Thailand,Asia,Northern Hemisphere,0
8759,QSV6764,28,Female,120,157/102,73,1,0,0,1,...,3.833038,217881,23.993866,617,4,9,Canada,North America,Northern Hemisphere,0
8760,XKA5925,47,Male,250,161/75,105,0,1,1,1,...,2.375214,36998,35.406146,527,4,4,Brazil,South America,Southern Hemisphere,1
8761,EPE6801,36,Male,178,119/67,60,1,0,1,0,...,0.029104,209943,27.294020,114,2,8,Brazil,South America,Southern Hemisphere,0
8762,ZWN9666,25,Female,356,138/67,75,1,1,0,0,...,9.005234,247338,32.914151,180,7,4,United Kingdom,Europe,Northern Hemisphere,1

In [66]:
df['Heart Attack Risk'].unique()

array([0, 1])

In [67]:
df.shape

(8763, 26)

In [68]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8763 entries, 0 to 8762
Data columns (total 26 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Patient ID                       8763 non-null   object
 1   Age                              8763 non-null   int64
 2   Sex                              8763 non-null   object
 3   Cholesterol                      8763 non-null   int64
 4   Blood Pressure                   8763 non-null   object
 5   Heart Rate                       8763 non-null   int64
 6   Diabetes                         8763 non-null   int64
 7   Family History                   8763 non-null   int64
 8   Smoking                          8763 non-null   int64
 9   Obesity                          8763 non-null   int64
 10  Alcohol Consumption              8763 non-null   int64
 11  Exercise Hours Per Week          8763 non-null   float64
 12  Diet                             8763 non-null   object
 13  Previous Heart Problems          8763 non-null   int64
 14  Medication Use                   8763 non-null   int64
 15  Stress Level                     8763 non-null   int64
 16  Sedentary Hours Per Day          8763 non-null   float64
 17  Income                           8763 non-null   int64
 18  BMI                              8763 non-null   float64
 19  Triglycerides                    8763 non-null   int64
 20  Physical Activity Days Per Week  8763 non-null   int64
 21  Sleep Hours Per Day              8763 non-null   int64
 22  Country                          8763 non-null   object
 23  Continent                        8763 non-null   object
 24  Hemisphere                       8763 non-null   object
 25  Heart Attack Risk                8763 non-null   int64
dtypes: float64(3), int64(16), object(7)
memory usage: 1.7+ MB

In [69]:
df.isnull().sum()

Patient ID                         0
Age                                0
Sex                                0
Cholesterol                        0
Blood Pressure                     0
Heart Rate                         0
Diabetes                           0
Family History                     0
Smoking                            0
Obesity                            0
Alcohol Consumption                0
Exercise Hours Per Week            0
Diet                               0
Previous Heart Problems            0
Medication Use                     0
Stress Level                       0
Sedentary Hours Per Day            0
Income                             0
BMI                                0
Triglycerides                      0
Physical Activity Days Per Week    0
Sleep Hours Per Day                0
Country                            0
Continent                          0
Hemisphere                         0
Heart Attack Risk                  0
dtype: int64

In [70]:
df.duplicated().sum()

np.int64(0)

In [71]:
df

,Patient ID,Age,Sex,Cholesterol,Blood Pressure,Heart Rate,Diabetes,Family History,Smoking,Obesity,...,Sedentary Hours Per Day,Income,BMI,Triglycerides,Physical Activity Days Per Week,Sleep Hours Per Day,Country,Continent,Hemisphere,Heart Attack Risk
0,BMW7812,67,Male,208,158/88,72,0,0,1,0,...,6.615001,261404,31.251233,286,0,6,Argentina,South America,Southern Hemisphere,0
1,CZE1114,21,Male,389,165/93,98,1,1,1,1,...,4.963459,285768,27.194973,235,1,7,Canada,North America,Northern Hemisphere,0
2,BNI9906,21,Female,324,174/99,72,1,0,0,0,...,9.463426,235282,28.176571,587,4,4,France,Europe,Northern Hemisphere,0
3,JLN3497,84,Male,383,163/100,73,1,1,1,0,...,7.648981,125640,36.464704,378,3,4,Canada,North America,Northern Hemisphere,0
4,GFO8847,66,Male,318,91/88,93,1,1,1,1,...,1.514821,160555,21.809144,231,1,5,Thailand,Asia,Northern Hemisphere,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8758,MSV9918,60,Male,121,94/76,61,1,1,1,0,...,10.806373,235420,19.655895,67,7,7,Thailand,Asia,Northern Hemisphere,0
8759,QSV6764,28,Female,120,157/102,73,1,0,0,1,...,3.833038,217881,23.993866,617,4,9,Canada,North America,Northern Hemisphere,0
8760,XKA5925,47,Male,250,161/75,105,0,1,1,1,...,2.375214,36998,35.406146,527,4,4,Brazil,South America,Southern Hemisphere,1
8761,EPE6801,36,Male,178,119/67,60,1,0,1,0,...,0.029104,209943,27.294020,114,2,8,Brazil,South America,Southern Hemisphere,0
8762,ZWN9666,25,Female,356,138/67,75,1,1,0,0,...,9.005234,247338,32.914151,180,7,4,United Kingdom,Europe,Northern Hemisphere,1

In [72]:
df.columns

Index(['Patient ID', 'Age', 'Sex', 'Cholesterol', 'Blood Pressure',
       'Heart Rate', 'Diabetes', 'Family History', 'Smoking', 'Obesity',
       'Alcohol Consumption', 'Exercise Hours Per Week', 'Diet',
       'Previous Heart Problems', 'Medication Use', 'Stress Level',
       'Sedentary Hours Per Day', 'Income', 'BMI', 'Triglycerides',
       'Physical Activity Days Per Week', 'Sleep Hours Per Day', 'Country',
       'Continent', 'Hemisphere', 'Heart Attack Risk'],
      dtype='object')

In [73]:
df['Country'].unique()

array(['Argentina', 'Canada', 'France', 'Thailand', 'Germany', 'Japan',
       'Brazil', 'South Africa', 'United States', 'Vietnam', 'China',
       'Italy', 'Spain', 'India', 'Nigeria', 'New Zealand', 'South Korea',
       'Australia', 'Colombia', 'United Kingdom'], dtype=object)

In [74]:
df['Continent'].unique()

array(['South America', 'North America', 'Europe', 'Asia', 'Africa',
       'Australia'], dtype=object)

In [75]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8763 entries, 0 to 8762
Data columns (total 26 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Patient ID                       8763 non-null   object
 1   Age                              8763 non-null   int64
 2   Sex                              8763 non-null   object
 3   Cholesterol                      8763 non-null   int64
 4   Blood Pressure                   8763 non-null   object
 5   Heart Rate                       8763 non-null   int64
 6   Diabetes                         8763 non-null   int64
 7   Family History                   8763 non-null   int64
 8   Smoking                          8763 non-null   int64
 9   Obesity                          8763 non-null   int64
 10  Alcohol Consumption              8763 non-null   int64
 11  Exercise Hours Per Week          8763 non-null   float64
 12  Diet                             8763 non-null   object
 13  Previous Heart Problems          8763 non-null   int64
 14  Medication Use                   8763 non-null   int64
 15  Stress Level                     8763 non-null   int64
 16  Sedentary Hours Per Day          8763 non-null   float64
 17  Income                           8763 non-null   int64
 18  BMI                              8763 non-null   float64
 19  Triglycerides                    8763 non-null   int64
 20  Physical Activity Days Per Week  8763 non-null   int64
 21  Sleep Hours Per Day              8763 non-null   int64
 22  Country                          8763 non-null   object
 23  Continent                        8763 non-null   object
 24  Hemisphere                       8763 non-null   object
 25  Heart Attack Risk                8763 non-null   int64
dtypes: float64(3), int64(16), object(7)
memory usage: 1.7+ MB

In [76]:
df['Heart Attack Risk'].value_counts()

Heart Attack Risk
0    5624
1    3139
Name: count, dtype: int64

In [77]:
# chi square - hypo

In [78]:
from scipy.stats import chi2_contingency
table = pd.crosstab(df['Sex'], df['Heart Attack Risk'])
print(table)

chi2, p, dof, expected = chi2_contingency(table)
alpha = 0.05
print(f'Chi2: {chi2:.2f}, p-value: {p:.4f}, Degrees of freedom: {dof}')

Heart Attack Risk     0     1
Sex
Female             1708   944
Male               3916  2195
Chi2: 0.07, p-value: 0.7906, Degrees of freedom: 1

In [79]:
if p < alpha:
    print('relation')
else:
    print('No relation')

No relation

In [80]:
from scipy.stats import chi2_contingency
table = pd.crosstab(df['Diet'], df['Heart Attack Risk'])
print(table)

chi2, p, dof, expected = chi2_contingency(table)
alpha = 0.05
print(f'Chi2: {chi2:.2f}, p-value: {p:.4f}, Degrees of freedom: {dof}')

Heart Attack Risk     0     1
Diet
Average            1886  1026
Healthy            1881  1079
Unhealthy          1857  1034
Chi2: 0.95, p-value: 0.6204, Degrees of freedom: 2

In [81]:
if p < alpha:
    print('relation')
else:
    print('No relation')

No relation

In [82]:
from scipy.stats import chi2_contingency
table = pd.crosstab(df['Country'], df['Heart Attack Risk'])
print(table)

chi2, p, dof, expected = chi2_contingency(table)
alpha = 0.05
print(f'Chi2: {chi2:.2f}, p-value: {p:.4f}, Degrees of freedom: {dof}')

Heart Attack Risk    0    1
Country
Argentina          297  174
Australia          281  168
Brazil             299  163
Canada             282  158
China              281  155
Colombia           267  162
France             289  157
Germany            305  172
India              283  129
Italy              295  136
Japan              289  144
New Zealand        284  151
Nigeria            270  178
South Africa       281  144
South Korea        246  163
Spain              280  150
Thailand           267  161
United Kingdom     297  160
United States      254  166
Vietnam            277  148
Chi2: 20.30, p-value: 0.3767, Degrees of freedom: 19

In [83]:
if p < alpha:
    print('relation')
else:
    print('No relation')

No relation

In [84]:
from scipy.stats import chi2_contingency
table = pd.crosstab(df['Continent'], df['Heart Attack Risk'])
print(table)

chi2, p, dof, expected = chi2_contingency(table)
alpha = 0.05
print(f'Chi2: {chi2:.2f}, p-value: {p:.4f}, Degrees of freedom: {dof}')

Heart Attack Risk     0    1
Continent
Africa              551  322
Asia               1643  900
Australia           565  319
Europe             1466  775
North America       536  324
South America       863  499
Chi2: 3.83, p-value: 0.5734, Degrees of freedom: 5

In [85]:
if p < alpha:
    print('relation')
else:
    print('No relation')

No relation

In [86]:
from scipy.stats import chi2_contingency
table = pd.crosstab(df['Hemisphere'], df['Heart Attack Risk'])
print(table)

chi2, p, dof, expected = chi2_contingency(table)
alpha = 0.05
print(f'Chi2: {chi2:.2f}, p-value: {p:.4f}, Degrees of freedom: {dof}')

Heart Attack Risk       0     1
Hemisphere
Northern Hemisphere  3607  2053
Southern Hemisphere  2017  1086
Chi2: 1.36, p-value: 0.2436, Degrees of freedom: 1

In [87]:
if p < alpha:
    print('relation')
else:
    print('No relation')

No relation

In [88]:
df.drop(columns='Sex', inplace = True)
df.drop(columns='Diet', inplace = True)
df.drop(columns='Country', inplace = True)
df.drop(columns='Continent', inplace = True)
df.drop(columns='Hemisphere', inplace = True)

In [89]:
df.columns

Index(['Patient ID', 'Age', 'Cholesterol', 'Blood Pressure', 'Heart Rate',
       'Diabetes', 'Family History', 'Smoking', 'Obesity',
       'Alcohol Consumption', 'Exercise Hours Per Week',
       'Previous Heart Problems', 'Medication Use', 'Stress Level',
       'Sedentary Hours Per Day', 'Income', 'BMI', 'Triglycerides',
       'Physical Activity Days Per Week', 'Sleep Hours Per Day',
       'Heart Attack Risk'],
      dtype='object')

In [90]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8763 entries, 0 to 8762
Data columns (total 21 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Patient ID                       8763 non-null   object
 1   Age                              8763 non-null   int64
 2   Cholesterol                      8763 non-null   int64
 3   Blood Pressure                   8763 non-null   object
 4   Heart Rate                       8763 non-null   int64
 5   Diabetes                         8763 non-null   int64
 6   Family History                   8763 non-null   int64
 7   Smoking                          8763 non-null   int64
 8   Obesity                          8763 non-null   int64
 9   Alcohol Consumption              8763 non-null   int64
 10  Exercise Hours Per Week          8763 non-null   float64
 11  Previous Heart Problems          8763 non-null   int64
 12  Medication Use                   8763 non-null   int64
 13  Stress Level                     8763 non-null   int64
 14  Sedentary Hours Per Day          8763 non-null   float64
 15  Income                           8763 non-null   int64
 16  BMI                              8763 non-null   float64
 17  Triglycerides                    8763 non-null   int64
 18  Physical Activity Days Per Week  8763 non-null   int64
 19  Sleep Hours Per Day              8763 non-null   int64
 20  Heart Attack Risk                8763 non-null   int64
dtypes: float64(3), int64(16), object(2)
memory usage: 1.4+ MB

In [91]:
df

,Patient ID,Age,Cholesterol,Blood Pressure,Heart Rate,Diabetes,Family History,Smoking,Obesity,Alcohol Consumption,...,Previous Heart Problems,Medication Use,Stress Level,Sedentary Hours Per Day,Income,BMI,Triglycerides,Physical Activity Days Per Week,Sleep Hours Per Day,Heart Attack Risk
0,BMW7812,67,208,158/88,72,0,0,1,0,0,...,0,0,9,6.615001,261404,31.251233,286,0,6,0
1,CZE1114,21,389,165/93,98,1,1,1,1,1,...,1,0,1,4.963459,285768,27.194973,235,1,7,0
2,BNI9906,21,324,174/99,72,1,0,0,0,0,...,1,1,9,9.463426,235282,28.176571,587,4,4,0
3,JLN3497,84,383,163/100,73,1,1,1,0,1,...,1,0,9,7.648981,125640,36.464704,378,3,4,0
4,GFO8847,66,318,91/88,93,1,1,1,1,0,...,1,0,6,1.514821,160555,21.809144,231,1,5,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8758,MSV9918,60,121,94/76,61,1,1,1,0,1,...,1,1,8,10.806373,235420,19.655895,67,7,7,0
8759,QSV6764,28,120,157/102,73,1,0,0,1,0,...,0,0,8,3.833038,217881,23.993866,617,4,9,0
8760,XKA5925,47,250,161/75,105,0,1,1,1,1,...,1,0,5,2.375214,36998,35.406146,527,4,4,1
8761,EPE6801,36,178,119/67,60,1,0,1,0,0,...,1,1,5,0.029104,209943,27.294020,114,2,8,0
8762,ZWN9666,25,356,138/67,75,1,1,0,0,1,...,0,0,8,9.005234,247338,32.914151,180,7,4,1

In [92]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8763 entries, 0 to 8762
Data columns (total 21 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Patient ID                       8763 non-null   object
 1   Age                              8763 non-null   int64
 2   Cholesterol                      8763 non-null   int64
 3   Blood Pressure                   8763 non-null   object
 4   Heart Rate                       8763 non-null   int64
 5   Diabetes                         8763 non-null   int64
 6   Family History                   8763 non-null   int64
 7   Smoking                          8763 non-null   int64
 8   Obesity                          8763 non-null   int64
 9   Alcohol Consumption              8763 non-null   int64
 10  Exercise Hours Per Week          8763 non-null   float64
 11  Previous Heart Problems          8763 non-null   int64
 12  Medication Use                   8763 non-null   int64
 13  Stress Level                     8763 non-null   int64
 14  Sedentary Hours Per Day          8763 non-null   float64
 15  Income                           8763 non-null   int64
 16  BMI                              8763 non-null   float64
 17  Triglycerides                    8763 non-null   int64
 18  Physical Activity Days Per Week  8763 non-null   int64
 19  Sleep Hours Per Day              8763 non-null   int64
 20  Heart Attack Risk                8763 non-null   int64
dtypes: float64(3), int64(16), object(2)
memory usage: 1.4+ MB

In [93]:
df = df.rename(columns={
    'Heart Attack Risk': 'Heart_Attack_Risk',
    'Heart Rate': 'Heart_Rate',
    'Family History': 'Family_History',
    'Alcohol Consumption': 'Alcohol_Consumption',
    'Exercise Hours Per Week': 'Exercise_Hours_Per_Week',
    'Previous Heart Problems': 'Previous_Heart_Problems',
    'Medication Use': 'Medication_Use',
    'Stress Level': 'Stress_Level',
    'Sedentary Hours Per Day': 'Sedentary_Hours_Per_Day',
    'Physical Activity Days Per Week': 'Physical_Activity_Days_Per_Week',
    'Sleep Hours Per Day': 'Sleep_Hours_Per_Day'
})

In [94]:
from statsmodels.formula.api import ols
from statsmodels.stats.anova import _get_covariance, anova_lm

formula = 'Heart_Attack_Risk ~ Age + Cholesterol + Heart_Rate + Diabetes + Family_History + Smoking + Obesity + Alcohol_Consumption + Exercise_Hours_Per_Week + Previous_Heart_Problems + Medication_Use + Stress_Level + Sedentary_Hours_Per_Day + Income + BMI + Triglycerides + Physical_Activity_Days_Per_Week + Sleep_Hours_Per_Day'

model = ols(formula, df).fit()
aov_table = anova_lm(model)
print(aov_table)
print(aov_table['PR(>F)'])

                                     df       sum_sq   mean_sq         F  \
Age                                 1.0     0.082599  0.082599  0.359194
Cholesterol                         1.0     0.758112  0.758112  3.296754
Heart_Rate                          1.0     0.036082  0.036082  0.156906
Diabetes                            1.0     0.624800  0.624800  2.717026
Family_History                      1.0     0.002436  0.002436  0.010595
Smoking                             1.0     0.120955  0.120955  0.525990
Obesity                             1.0     0.344880  0.344880  1.499759
Alcohol_Consumption                 1.0     0.386908  0.386908  1.682524
Exercise_Hours_Per_Week             1.0     0.233650  0.233650  1.016059
Previous_Heart_Problems             1.0     0.000489  0.000489  0.002127
Medication_Use                      1.0     0.010466  0.010466  0.045512
Stress_Level                        1.0     0.028874  0.028874  0.125563
Sedentary_Hours_Per_Day             1.0     0.085513  0.085513  0.371866
Income                              1.0     0.186524  0.186524  0.811124
BMI                                 1.0     0.000141  0.000141  0.000614
Triglycerides                       1.0     0.218454  0.218454  0.949979
Physical_Activity_Days_Per_Week     1.0     0.055323  0.055323  0.240581
Sleep_Hours_Per_Day                 1.0     0.655377  0.655377  2.849995
Residual                         8744.0  2010.745159  0.229957       NaN

                                   PR(>F)
Age                              0.548970
Cholesterol                      0.069451
Heart_Rate                       0.692031
Diabetes                         0.099319
Family_History                   0.918020
Smoking                          0.468317
Obesity                          0.220741
Alcohol_Consumption              0.194624
Exercise_Hours_Per_Week          0.313483
Previous_Heart_Problems          0.963216
Medication_Use                   0.831071
Stress_Level                     0.723087
Sedentary_Hours_Per_Day          0.542005
Income                           0.367813
BMI                              0.980226
Triglycerides                    0.329752
Physical_Activity_Days_Per_Week  0.623799
Sleep_Hours_Per_Day              0.091410
Residual                              NaN
Age                                0.548970
Cholesterol                        0.069451
Heart_Rate                         0.692031
Diabetes                           0.099319
Family_History                     0.918020
Smoking                            0.468317
Obesity                            0.220741
Alcohol_Consumption                0.194624
Exercise_Hours_Per_Week            0.313483
Previous_Heart_Problems            0.963216
Medication_Use                     0.831071
Stress_Level                       0.723087
Sedentary_Hours_Per_Day            0.542005
Income                             0.367813
BMI                                0.980226
Triglycerides                      0.329752
Physical_Activity_Days_Per_Week    0.623799
Sleep_Hours_Per_Day                0.091410
Residual                                NaN
Name: PR(>F), dtype: float64

In [95]:
print(aov_table['PR(>F)'])

Age                                0.548970
Cholesterol                        0.069451
Heart_Rate                         0.692031
Diabetes                           0.099319
Family_History                     0.918020
Smoking                            0.468317
Obesity                            0.220741
Alcohol_Consumption                0.194624
Exercise_Hours_Per_Week            0.313483
Previous_Heart_Problems            0.963216
Medication_Use                     0.831071
Stress_Level                       0.723087
Sedentary_Hours_Per_Day            0.542005
Income                             0.367813
BMI                                0.980226
Triglycerides                      0.329752
Physical_Activity_Days_Per_Week    0.623799
Sleep_Hours_Per_Day                0.091410
Residual                                NaN
Name: PR(>F), dtype: float64

In [96]:
df.drop(['Age', 'Cholesterol', 'Heart_Rate', 'Diabetes', 'Family_History', 'Smoking', 'Obesity', 'Alcohol_Consumption', 'Exercise_Hours_Per_Week', 'Previous_Heart_Problems', 'Medication_Use', 'Stress_Level', 'Sedentary_Hours_Per_Day', 'Income', 'BMI', 'Triglycerides', 'Physical_Activity_Days_Per_Week', 'Sleep_Hours_Per_Day'], axis=1, inplace=True)

In [97]:
df.columns

Index(['Patient ID', 'Blood Pressure', 'Heart_Attack_Risk'], dtype='object')

In [98]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8763 entries, 0 to 8762
Data columns (total 3 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Patient ID         8763 non-null   object
 1   Blood Pressure     8763 non-null   object
 2   Heart_Attack_Risk  8763 non-null   int64
dtypes: int64(1), object(2)
memory usage: 205.5+ KB

In [99]:
df.drop(columns='Patient ID', inplace=True)

In [100]:
df

     Blood Pressure  Heart_Attack_Risk
0            158/88                  0
1            165/93                  0
2            174/99                  0
3           163/100                  0
4             91/88                  0
...             ...                ...
8758          94/76                  0
8759        157/102                  0
8760         161/75                  1
8761         119/67                  0
8762         138/67                  1

[8763 rows x 2 columns]

In [101]:
from sklearn.preprocessing import OrdinalEncoder
o = OrdinalEncoder()

df[['Blood Pressure']] = o.fit_transform(df[['Blood Pressure']])

In [102]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8763 entries, 0 to 8762
Data columns (total 2 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Blood Pressure     8763 non-null   float64
 1   Heart_Attack_Risk  8763 non-null   int64
dtypes: float64(1), int64(1)
memory usage: 137.1 KB

In [103]:
from sklearn.model_selection import train_test_split

x = df.drop('Heart_Attack_Risk', axis=1)
y = df['Heart_Attack_Risk']

x_train,x_test,y_train,y_test=train_test_split(x,y, test_size=0.20,random_state=42, stratify=y)
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(7010, 1)
(1753, 1)
(7010,)
(1753,)

In [104]:
df['Heart_Attack_Risk'].value_counts()

Heart_Attack_Risk
0    5624
1    3139
Name: count, dtype: int64

In [105]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

In [106]:
# LogisticReg - training

In [107]:
from sklearn.linear_model import LogisticRegression  
model = LogisticRegression(random_state=42, class_weight='balanced')
model.fit(x_train_scaled,y_train)
y_pred=model.predict(x_train_scaled)
y_pred

/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:451: OptimizeWarning: Unknown solver options: iprint
  opt_res = optimize.minimize(

array([0, 0, 0, ..., 1, 1, 0], shape=(7010,))

In [108]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report  
print(accuracy_score(y_train,y_pred))
print(confusion_matrix(y_train,y_pred))
print(classification_report(y_train,y_pred))

0.5015691868758916
[[2266 2233]
 [1261 1250]]
              precision    recall  f1-score   support

           0       0.64      0.50      0.56      4499
           1       0.36      0.50      0.42      2511

    accuracy                           0.50      7010
   macro avg       0.50      0.50      0.49      7010
weighted avg       0.54      0.50      0.51      7010

In [109]:
# LogisticReg - testing

In [110]:
y_pred=model.predict(x_test_scaled)
y_pred

array([0, 1, 0, ..., 0, 0, 1], shape=(1753,))

In [111]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report  
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

0.5037079292641187
[[548 577]
 [293 335]]
              precision    recall  f1-score   support

           0       0.65      0.49      0.56      1125
           1       0.37      0.53      0.44       628

    accuracy                           0.50      1753
   macro avg       0.51      0.51      0.50      1753
weighted avg       0.55      0.50      0.51      1753

In [112]:
# Decisiontree - training -> with parameters

In [113]:
from sklearn.tree import DecisionTreeClassifier  
dt=DecisionTreeClassifier(random_state=42, max_depth=4, min_samples_split=2, min_samples_leaf=1, class_weight='balanced')
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)
dt.fit(x_train_scaled,y_train)
y_pred=dt.predict(x_train_scaled)
y_pred

array([1, 1, 1, ..., 1, 1, 1], shape=(7010,))

In [114]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
print(accuracy_score(y_train, y_pred))
print(confusion_matrix(y_train, y_pred))
print(classification_report(y_train, y_pred))

0.38216833095577746
[[ 259 4240]
 [  91 2420]]
              precision    recall  f1-score   support

           0       0.74      0.06      0.11      4499
           1       0.36      0.96      0.53      2511

    accuracy                           0.38      7010
   macro avg       0.55      0.51      0.32      7010
weighted avg       0.61      0.38      0.26      7010

In [115]:
# Decisiontree - testing

In [116]:
y_pred=dt.predict(x_test_scaled)
y_pred

array([1, 1, 1, ..., 1, 1, 0], shape=(1753,))

In [117]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
print(accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

0.3690815744438106
[[  49 1076]
 [  30  598]]
              precision    recall  f1-score   support

           0       0.62      0.04      0.08      1125
           1       0.36      0.95      0.52       628

    accuracy                           0.37      1753
   macro avg       0.49      0.50      0.30      1753
weighted avg       0.53      0.37      0.24      1753

In [118]:
# Decisiontree - training -> without parameters

In [119]:
from sklearn.tree import DecisionTreeClassifier  
dt=DecisionTreeClassifier()
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)
dt.fit(x_train_scaled,y_train)
y_pred=dt.predict(x_train_scaled)
y_pred

array([0, 0, 0, ..., 0, 0, 0], shape=(7010,))

In [120]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
print(accuracy_score(y_train, y_pred))
print(confusion_matrix(y_train, y_pred))
print(classification_report(y_train, y_pred))

0.8109843081312411
[[4275  224]
 [1101 1410]]
              precision    recall  f1-score   support

           0       0.80      0.95      0.87      4499
           1       0.86      0.56      0.68      2511

    accuracy                           0.81      7010
   macro avg       0.83      0.76      0.77      7010
weighted avg       0.82      0.81      0.80      7010

In [121]:
# Decisiontree - testing

In [122]:
y_pred=dt.predict(x_test_scaled)
y_pred

array([0, 0, 0, ..., 0, 0, 1], shape=(1753,))

In [123]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
print(accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

0.5693097547062179
[[829 296]
 [459 169]]
              precision    recall  f1-score   support

           0       0.64      0.74      0.69      1125
           1       0.36      0.27      0.31       628

    accuracy                           0.57      1753
   macro avg       0.50      0.50      0.50      1753
weighted avg       0.54      0.57      0.55      1753