In [7]:
# https://www.kaggle.com/datasets/kundanbedmutha/hotel-booking-reservation

In [8]:
import pandas as pd

In [9]:
df = pd.read_csv("hotel_bookings_updated_2024.csv")

In [10]:
df

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date,city
0,Resort Hotel - Chandigarh,0,342,2024,July,30,27,0,0,2,...,NaN,NaN,0,Transient,0.00,0,0,Check-Out,2024-07-27 22:16:40.916332324,Chandigarh
1,Resort Hotel - Mumbai,0,737,2024,April,17,28,0,0,2,...,NaN,NaN,0,Transient,0.00,0,0,Check-Out,2024-04-28 21:56:21.507509066,Mumbai
2,Resort Hotel - Delhi,0,7,2024,September,37,10,0,1,1,...,NaN,NaN,0,Transient,75.00,0,0,Check-Out,2024-09-10 03:46:25.734029096,Delhi
3,Resort Hotel - Kolkata,0,13,2024,August,33,14,0,1,1,...,304.0,NaN,0,Transient,75.00,0,0,Check-Out,2024-08-14 18:07:10.049669568,Kolkata
4,Resort Hotel - Lucknow,0,14,2024,September,37,14,0,2,2,...,240.0,NaN,0,Transient,98.00,0,1,Check-Out,2024-09-14 14:27:32.473846000,Lucknow
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119385,City Hotel - Pune,0,23,2024,September,39,29,2,5,2,...,394.0,NaN,0,Transient,96.14,0,0,Check-Out,2024-09-29 05:33:06.002060492,Pune
119386,City Hotel - Mumbai,0,102,2024,November,46,16,2,5,3,...,9.0,NaN,0,Transient,225.43,0,2,Check-Out,2024-11-16 01:55:18.426320680,Mumbai
119387,City Hotel - Lucknow,0,34,2024,April,16,19,2,5,2,...,9.0,NaN,0,Transient,157.71,0,4,Check-Out,2024-04-19 07:50:22.982016768,Lucknow
119388,City Hotel - Ahmedabad,0,109,2024,October,40,5,2,5,2,...,89.0,NaN,0,Transient,104.40,0,0,Check-Out,2024-10-05 12:37:40.429352788,Ahmedabad
119389,City Hotel - Bhopal,0,205,2024,December,51,21,2,7,2,...,9.0,NaN,0,Transient,151.20,0,2,Check-Out,2024-12-21 07:11:08.111802592,Bhopal

In [14]:
df['customer_type'].unique()

array(['Transient', 'Contract', 'Transient-Party', 'Group'], dtype=object)

In [ ]:
df.shape

(119390, 33)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119390 entries, 0 to 119389
Data columns (total 33 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   hotel                           119390 non-null  object
 1   is_canceled                     119390 non-null  int64
 2   lead_time                       119390 non-null  int64
 3   arrival_date_year               119390 non-null  int64
 4   arrival_date_month              119390 non-null  object
 5   arrival_date_week_number        119390 non-null  int64
 6   arrival_date_day_of_month       119390 non-null  int64
 7   stays_in_weekend_nights         119390 non-null  int64
 8   stays_in_week_nights            119390 non-null  int64
 9   adults                          119390 non-null  int64
 10  children                        119386 non-null  float64
 11  babies                          119390 non-null  int64
 12  meal                            119390 non-null  object
 13  country                         118902 non-null  object
 14  market_segment                  119390 non-null  object
 15  distribution_channel            119390 non-null  object
 16  is_repeated_guest               119390 non-null  int64
 17  previous_cancellations          119390 non-null  int64
 18  previous_bookings_not_canceled  119390 non-null  int64
 19  reserved_room_type              119390 non-null  object
 20  assigned_room_type              119390 non-null  object
 21  booking_changes                 119390 non-null  int64
 22  deposit_type                    119390 non-null  object
 23  agent                           103050 non-null  float64
 24  company                         6797 non-null    float64
 25  days_in_waiting_list            119390 non-null  int64
 26  customer_type                   119390 non-null  object
 27  adr                             119390 non-null  float64
 28  required_car_parking_spaces     119390 non-null  int64
 29  total_of_special_requests       119390 non-null  int64
 30  reservation_status              119390 non-null  object
 31  reservation_status_date         119390 non-null  object
 32  city                            119390 non-null  object
dtypes: float64(4), int64(16), object(13)
memory usage: 30.1+ MB

In [ ]:
df['country']

0         PRT
1         PRT
2         GBR
3         GBR
4         GBR
         ...
119385    BEL
119386    FRA
119387    DEU
119388    GBR
119389    DEU
Name: country, Length: 119390, dtype: object

check for null

In [ ]:
df.isnull().sum()

hotel                                  0
is_canceled                            0
lead_time                              0
arrival_date_year                      0
arrival_date_month                     0
arrival_date_week_number               0
arrival_date_day_of_month              0
stays_in_weekend_nights                0
stays_in_week_nights                   0
adults                                 0
children                               4
babies                                 0
meal                                   0
country                              488
market_segment                         0
distribution_channel                   0
is_repeated_guest                      0
previous_cancellations                 0
previous_bookings_not_canceled         0
reserved_room_type                     0
assigned_room_type                     0
booking_changes                        0
deposit_type                           0
agent                              16340
company                           112593
days_in_waiting_list                   0
customer_type                          0
adr                                    0
required_car_parking_spaces            0
total_of_special_requests              0
reservation_status                     0
reservation_status_date                0
city                                   0
dtype: int64

In [ ]:
# null => children, country, agent, company

In [ ]:
df['children'].value_counts()

children
0.0     110796
1.0       4861
2.0       3652
3.0         76
10.0         1
Name: count, dtype: int64

In [ ]:
df['children'] = df['children'].fillna(df['children'].median())

In [ ]:
df['children'].value_counts()

children
0.0     110800
1.0       4861
2.0       3652
3.0         76
10.0         1
Name: count, dtype: int64

In [ ]:
df.isnull().sum()

hotel                                  0
is_canceled                            0
lead_time                              0
arrival_date_year                      0
arrival_date_month                     0
arrival_date_week_number               0
arrival_date_day_of_month              0
stays_in_weekend_nights                0
stays_in_week_nights                   0
adults                                 0
children                               0
babies                                 0
meal                                   0
country                              488
market_segment                         0
distribution_channel                   0
is_repeated_guest                      0
previous_cancellations                 0
previous_bookings_not_canceled         0
reserved_room_type                     0
assigned_room_type                     0
booking_changes                        0
deposit_type                           0
agent                              16340
company                           112593
days_in_waiting_list                   0
customer_type                          0
adr                                    0
required_car_parking_spaces            0
total_of_special_requests              0
reservation_status                     0
reservation_status_date                0
city                                   0
dtype: int64

In [ ]:
df['country']

0         PRT
1         PRT
2         GBR
3         GBR
4         GBR
         ...
119385    BEL
119386    FRA
119387    DEU
119388    GBR
119389    DEU
Name: country, Length: 119390, dtype: object

In [ ]:
# country -> object -> so use mode()

In [ ]:
# mode() - for categorical data (string) / ID's(unique numbers)
# mean() - numerical, symmetric
# median() - numerical, if values not evenly distributed, value is too far from other values

In [ ]:
df['country'].value_counts()

country
PRT    48590
GBR    12129
FRA    10415
ESP     8568
DEU     7287
       ...
DJI        1
BWA        1
HND        1
VGB        1
NAM        1
Name: count, Length: 177, dtype: int64

In [ ]:
df['country'] = df['country'].fillna(df['country'].mode()[0])

In [ ]:
df.isnull().sum()

hotel                                  0
is_canceled                            0
lead_time                              0
arrival_date_year                      0
arrival_date_month                     0
arrival_date_week_number               0
arrival_date_day_of_month              0
stays_in_weekend_nights                0
stays_in_week_nights                   0
adults                                 0
children                               0
babies                                 0
meal                                   0
country                                0
market_segment                         0
distribution_channel                   0
is_repeated_guest                      0
previous_cancellations                 0
previous_bookings_not_canceled         0
reserved_room_type                     0
assigned_room_type                     0
booking_changes                        0
deposit_type                           0
agent                              16340
company                           112593
days_in_waiting_list                   0
customer_type                          0
adr                                    0
required_car_parking_spaces            0
total_of_special_requests              0
reservation_status                     0
reservation_status_date                0
city                                   0
dtype: int64

In [ ]:
df['agent']

0           NaN
1           NaN
2           NaN
3         304.0
4         240.0
          ...
119385    394.0
119386      9.0
119387      9.0
119388     89.0
119389      9.0
Name: agent, Length: 119390, dtype: float64

In [ ]:
df['agent'].value_counts()

agent
9.0      31961
240.0    13922
1.0       7191
14.0      3640
7.0       3539
         ...
289.0        1
432.0        1
265.0        1
93.0         1
304.0        1
Name: count, Length: 333, dtype: int64

In [ ]:
# agent may be numerical, but they are unique ID values. so use mode

In [ ]:
df['agent'] = df['agent'].fillna(df['agent'].mode()[0])

In [ ]:
df.isnull().sum()

hotel                                  0
is_canceled                            0
lead_time                              0
arrival_date_year                      0
arrival_date_month                     0
arrival_date_week_number               0
arrival_date_day_of_month              0
stays_in_weekend_nights                0
stays_in_week_nights                   0
adults                                 0
children                               0
babies                                 0
meal                                   0
country                                0
market_segment                         0
distribution_channel                   0
is_repeated_guest                      0
previous_cancellations                 0
previous_bookings_not_canceled         0
reserved_room_type                     0
assigned_room_type                     0
booking_changes                        0
deposit_type                           0
agent                                  0
company                           112593
days_in_waiting_list                   0
customer_type                          0
adr                                    0
required_car_parking_spaces            0
total_of_special_requests              0
reservation_status                     0
reservation_status_date                0
city                                   0
dtype: int64

In [ ]:
df['company'].head(1000)

0     NaN
1     NaN
2     NaN
3     NaN
4     NaN
       ..
995   NaN
996   NaN
997   NaN
998   NaN
999   NaN
Name: company, Length: 1000, dtype: float64

In [ ]:
df['company'].isnull()

0         True
1         True
2         True
3         True
4         True
          ...
119385    True
119386    True
119387    True
119388    True
119389    True
Name: company, Length: 119390, dtype: bool

In [ ]:
df['company'].isnull().sum()

np.int64(112593)

In [ ]:
df['company'].unique()

array([ nan, 110., 113., 270., 178., 240., 154., 144., 307., 268.,  59.,
       204., 312., 318.,  94., 174., 274., 195., 223., 317., 281., 118.,
        53., 286.,  12.,  47., 324., 342., 373., 371., 383.,  86.,  82.,
       218.,  88.,  31., 397., 392., 405., 331., 367.,  20.,  83., 416.,
        51., 395., 102.,  34.,  84., 360., 394., 457., 382., 461., 478.,
       386., 112., 486., 421.,   9., 308., 135., 224., 504., 269., 356.,
       498., 390., 513., 203., 263., 477., 521., 169., 515., 445., 337.,
       251., 428., 292., 388., 130., 250., 355., 254., 543., 531., 528.,
        62., 120.,  42.,  81., 116., 530., 103.,  39.,  16.,  92.,  61.,
       501., 165., 291., 290.,  43., 325., 192., 108., 200., 465., 287.,
       297., 490., 482., 207., 282., 437., 225., 329., 272.,  28.,  77.,
       338.,  72., 246., 319., 146., 159., 380., 323., 511., 407., 278.,
        80., 403., 399.,  14., 137., 343., 346., 347., 349., 289., 351.,
       353.,  54.,  99., 358., 361., 362., 366., 372., 365., 277., 109.,
       377., 379.,  22., 378., 330., 364., 401., 232., 255., 384., 167.,
       212., 514., 391., 400., 376., 402., 396., 302., 398.,   6., 370.,
       369., 409., 168., 104., 408., 413., 148.,  10., 333., 419., 415.,
       424., 425., 423., 422., 435., 439., 442., 448., 443., 454., 444.,
        52., 459., 458., 456., 460., 447., 470., 466., 484., 184., 485.,
        32., 487., 491., 494., 193., 516., 496., 499.,  29.,  78., 520.,
       507., 506., 512., 126.,  64., 242., 518., 523., 539., 534., 436.,
       525., 541.,  40., 455., 410.,  45.,  38.,  49.,  48.,  67.,  68.,
        65.,  91.,  37.,   8., 179., 209., 219., 221., 227., 153., 186.,
       253., 202., 216., 275., 233., 280., 309., 321.,  93., 316.,  85.,
       107., 350., 279., 334., 348., 150.,  73., 385., 418., 197., 450.,
       452., 115.,  46.,  76.,  96., 100., 105., 101., 122.,  11., 139.,
       142., 127., 143., 140., 149., 163., 160., 180., 238., 183., 222.,
       185., 217., 215., 213., 237., 230., 234.,  35., 245., 158., 258.,
       259., 260., 411., 257., 271.,  18., 106., 210., 273.,  71., 284.,
       301., 305., 293., 264., 311., 304., 313., 288., 320., 314., 332.,
       341., 352., 243., 368., 393., 132., 220., 412., 420., 426., 417.,
       429., 433., 446., 357., 479., 483., 489., 229., 481., 497., 451.,
       492.])

In [ ]:
# for company many values are null, so fro now i'll use mode as it looks like ID

In [ ]:
df['company'] = df['company'].fillna(df['company'].mode()[0])

In [ ]:
df.isnull().sum()

hotel                             0
is_canceled                       0
lead_time                         0
arrival_date_year                 0
arrival_date_month                0
arrival_date_week_number          0
arrival_date_day_of_month         0
stays_in_weekend_nights           0
stays_in_week_nights              0
adults                            0
children                          0
babies                            0
meal                              0
country                           0
market_segment                    0
distribution_channel              0
is_repeated_guest                 0
previous_cancellations            0
previous_bookings_not_canceled    0
reserved_room_type                0
assigned_room_type                0
booking_changes                   0
deposit_type                      0
agent                             0
company                           0
days_in_waiting_list              0
customer_type                     0
adr                               0
required_car_parking_spaces       0
total_of_special_requests         0
reservation_status                0
reservation_status_date           0
city                              0
dtype: int64

In [ ]:
# find duplicate

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
# categorical columns -> float

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119390 entries, 0 to 119389
Data columns (total 33 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   hotel                           119390 non-null  object
 1   is_canceled                     119390 non-null  int64
 2   lead_time                       119390 non-null  int64
 3   arrival_date_year               119390 non-null  int64
 4   arrival_date_month              119390 non-null  object
 5   arrival_date_week_number        119390 non-null  int64
 6   arrival_date_day_of_month       119390 non-null  int64
 7   stays_in_weekend_nights         119390 non-null  int64
 8   stays_in_week_nights            119390 non-null  int64
 9   adults                          119390 non-null  int64
 10  children                        119390 non-null  float64
 11  babies                          119390 non-null  int64
 12  meal                            119390 non-null  object
 13  country                         119390 non-null  object
 14  market_segment                  119390 non-null  object
 15  distribution_channel            119390 non-null  object
 16  is_repeated_guest               119390 non-null  int64
 17  previous_cancellations          119390 non-null  int64
 18  previous_bookings_not_canceled  119390 non-null  int64
 19  reserved_room_type              119390 non-null  object
 20  assigned_room_type              119390 non-null  object
 21  booking_changes                 119390 non-null  int64
 22  deposit_type                    119390 non-null  object
 23  agent                           119390 non-null  float64
 24  company                         119390 non-null  float64
 25  days_in_waiting_list            119390 non-null  int64
 26  customer_type                   119390 non-null  object
 27  adr                             119390 non-null  float64
 28  required_car_parking_spaces     119390 non-null  int64
 29  total_of_special_requests       119390 non-null  int64
 30  reservation_status              119390 non-null  object
 31  reservation_status_date         119390 non-null  object
 32  city                            119390 non-null  object
dtypes: float64(4), int64(16), object(13)
memory usage: 30.1+ MB

In [ ]:
df['reservation_status_date'] 
# i have a doubt in this part

0         2024-07-27 22:16:40.916332324
1         2024-04-28 21:56:21.507509066
2         2024-09-10 03:46:25.734029096
3         2024-08-14 18:07:10.049669568
4         2024-09-14 14:27:32.473846000
                      ...
119385    2024-09-29 05:33:06.002060492
119386    2024-11-16 01:55:18.426320680
119387    2024-04-19 07:50:22.982016768
119388    2024-10-05 12:37:40.429352788
119389    2024-12-21 07:11:08.111802592
Name: reservation_status_date, Length: 119390, dtype: object

In [ ]:
df['hotel'].unique()

array(['Resort Hotel - Chandigarh', 'Resort Hotel - Mumbai',
       'Resort Hotel - Delhi', 'Resort Hotel - Kolkata',
       'Resort Hotel - Lucknow', 'Resort Hotel - Indore',
       'Resort Hotel - Ahmedabad', 'Resort Hotel - Pune',
       'Resort Hotel - Chennai', 'Resort Hotel - Bhopal',
       'Resort Hotel - Hyderabad', 'Resort Hotel - Kochi',
       'Resort Hotel - Bangalore', 'Resort Hotel - Jaipur',
       'Resort Hotel - Goa', 'City Hotel - Ahmedabad',
       'City Hotel - Indore', 'City Hotel - Jaipur', 'City Hotel - Pune',
       'City Hotel - Hyderabad', 'City Hotel - Bhopal',
       'City Hotel - Kolkata', 'City Hotel - Mumbai',
       'City Hotel - Bangalore', 'City Hotel - Lucknow',
       'City Hotel - Chennai', 'City Hotel - Chandigarh',
       'City Hotel - Delhi', 'City Hotel - Kochi', 'City Hotel - Goa'],
      dtype=object)

In [ ]:
df['hotel'].value_counts()

hotel
City Hotel - Ahmedabad       5405
City Hotel - Bhopal          5367
City Hotel - Jaipur          5343
City Hotel - Pune            5343
City Hotel - Kolkata         5339
City Hotel - Hyderabad       5339
City Hotel - Goa             5297
City Hotel - Chandigarh      5293
City Hotel - Lucknow         5290
City Hotel - Mumbai          5265
City Hotel - Delhi           5252
City Hotel - Chennai         5251
City Hotel - Bangalore       5210
City Hotel - Indore          5170
City Hotel - Kochi           5166
Resort Hotel - Bhopal        2737
Resort Hotel - Delhi         2726
Resort Hotel - Kochi         2723
Resort Hotel - Jaipur        2695
Resort Hotel - Bangalore     2687
Resort Hotel - Chandigarh    2685
Resort Hotel - Goa           2676
Resort Hotel - Chennai       2674
Resort Hotel - Mumbai        2670
Resort Hotel - Indore        2657
Resort Hotel - Pune          2649
Resort Hotel - Hyderabad     2642
Resort Hotel - Kolkata       2637
Resort Hotel - Ahmedabad     2623
Resort Hotel - Lucknow       2579
Name: count, dtype: int64

In [ ]:
df['hotel'].nunique()

30

In [ ]:
# encoding

In [ ]:
# # hotel - L, arrival_date_month - O, meal - O, country - L, market_segment - L , distribution_channel - L, reserved_room_type - O,  reservation_status_date - O, city - L

In [ ]:
# output (y) - is_cancelled, lead_time,

In [ ]:
df

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date,city
0,Resort Hotel - Chandigarh,0,342,2024,July,30,27,0,0,2,...,9.0,40.0,0,Transient,0.00,0,0,Check-Out,2024-07-27 22:16:40.916332324,Chandigarh
1,Resort Hotel - Mumbai,0,737,2024,April,17,28,0,0,2,...,9.0,40.0,0,Transient,0.00,0,0,Check-Out,2024-04-28 21:56:21.507509066,Mumbai
2,Resort Hotel - Delhi,0,7,2024,September,37,10,0,1,1,...,9.0,40.0,0,Transient,75.00,0,0,Check-Out,2024-09-10 03:46:25.734029096,Delhi
3,Resort Hotel - Kolkata,0,13,2024,August,33,14,0,1,1,...,304.0,40.0,0,Transient,75.00,0,0,Check-Out,2024-08-14 18:07:10.049669568,Kolkata
4,Resort Hotel - Lucknow,0,14,2024,September,37,14,0,2,2,...,240.0,40.0,0,Transient,98.00,0,1,Check-Out,2024-09-14 14:27:32.473846000,Lucknow
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119385,City Hotel - Pune,0,23,2024,September,39,29,2,5,2,...,394.0,40.0,0,Transient,96.14,0,0,Check-Out,2024-09-29 05:33:06.002060492,Pune
119386,City Hotel - Mumbai,0,102,2024,November,46,16,2,5,3,...,9.0,40.0,0,Transient,225.43,0,2,Check-Out,2024-11-16 01:55:18.426320680,Mumbai
119387,City Hotel - Lucknow,0,34,2024,April,16,19,2,5,2,...,9.0,40.0,0,Transient,157.71,0,4,Check-Out,2024-04-19 07:50:22.982016768,Lucknow
119388,City Hotel - Ahmedabad,0,109,2024,October,40,5,2,5,2,...,89.0,40.0,0,Transient,104.40,0,0,Check-Out,2024-10-05 12:37:40.429352788,Ahmedabad
119389,City Hotel - Bhopal,0,205,2024,December,51,21,2,7,2,...,9.0,40.0,0,Transient,151.20,0,2,Check-Out,2024-12-21 07:11:08.111802592,Bhopal

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119390 entries, 0 to 119389
Data columns (total 33 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   hotel                           119390 non-null  object
 1   is_canceled                     119390 non-null  int64
 2   lead_time                       119390 non-null  int64
 3   arrival_date_year               119390 non-null  int64
 4   arrival_date_month              119390 non-null  object
 5   arrival_date_week_number        119390 non-null  int64
 6   arrival_date_day_of_month       119390 non-null  int64
 7   stays_in_weekend_nights         119390 non-null  int64
 8   stays_in_week_nights            119390 non-null  int64
 9   adults                          119390 non-null  int64
 10  children                        119390 non-null  float64
 11  babies                          119390 non-null  int64
 12  meal                            119390 non-null  object
 13  country                         119390 non-null  object
 14  market_segment                  119390 non-null  object
 15  distribution_channel            119390 non-null  object
 16  is_repeated_guest               119390 non-null  int64
 17  previous_cancellations          119390 non-null  int64
 18  previous_bookings_not_canceled  119390 non-null  int64
 19  reserved_room_type              119390 non-null  object
 20  assigned_room_type              119390 non-null  object
 21  booking_changes                 119390 non-null  int64
 22  deposit_type                    119390 non-null  object
 23  agent                           119390 non-null  float64
 24  company                         119390 non-null  float64
 25  days_in_waiting_list            119390 non-null  int64
 26  customer_type                   119390 non-null  object
 27  adr                             119390 non-null  float64
 28  required_car_parking_spaces     119390 non-null  int64
 29  total_of_special_requests       119390 non-null  int64
 30  reservation_status              119390 non-null  object
 31  reservation_status_date         119390 non-null  object
 32  city                            119390 non-null  object
dtypes: float64(4), int64(16), object(13)
memory usage: 30.1+ MB

In [ ]:
df['market_segment']

0                Direct
1                Direct
2                Direct
3             Corporate
4             Online TA
              ...
119385    Offline TA/TO
119386        Online TA
119387        Online TA
119388        Online TA
119389        Online TA
Name: market_segment, Length: 119390, dtype: object

In [ ]:
df['meal'].unique()

array(['BB', 'FB', 'HB', 'SC', 'Undefined'], dtype=object)

In [ ]:
df['is_canceled'].head(100)

0     0
1     0
2     0
3     0
4     0
     ..
95    1
96    1
97    0
98    0
99    0
Name: is_canceled, Length: 100, dtype: int64

In [ ]:
df['meal']

0         BB
1         BB
2         BB
3         BB
4         BB
          ..
119385    BB
119386    BB
119387    BB
119388    BB
119389    HB
Name: meal, Length: 119390, dtype: object

In [ ]:
from sklearn.preprocessing import LabelEncoder
l = LabelEncoder()
df['hotel'] = l.fit_transform(df['hotel'])
df['country'] = l.fit_transform(df['country'])
df['market_segment'] = l.fit_transform(df['market_segment'])
df['distribution_channel'] = l.fit_transform(df['distribution_channel'])
df['city'] = l.fit_transform(df['city'])

In [ ]:
from sklearn.preprocessing import OrdinalEncoder
O = OrdinalEncoder()
df['arrival_date_month'] = l.fit_transform(df['arrival_date_month'])
df['meal'] = l.fit_transform(df['meal'])
df['reserved_room_type'] = l.fit_transform(df['reserved_room_type'])
df['reservation_status_date'] = l.fit_transform(df['reservation_status_date'])

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119390 entries, 0 to 119389
Data columns (total 33 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   hotel                           119390 non-null  int64
 1   is_canceled                     119390 non-null  int64
 2   lead_time                       119390 non-null  int64
 3   arrival_date_year               119390 non-null  int64
 4   arrival_date_month              119390 non-null  int64
 5   arrival_date_week_number        119390 non-null  int64
 6   arrival_date_day_of_month       119390 non-null  int64
 7   stays_in_weekend_nights         119390 non-null  int64
 8   stays_in_week_nights            119390 non-null  int64
 9   adults                          119390 non-null  int64
 10  children                        119390 non-null  float64
 11  babies                          119390 non-null  int64
 12  meal                            119390 non-null  int64
 13  country                         119390 non-null  int64
 14  market_segment                  119390 non-null  int64
 15  distribution_channel            119390 non-null  int64
 16  is_repeated_guest               119390 non-null  int64
 17  previous_cancellations          119390 non-null  int64
 18  previous_bookings_not_canceled  119390 non-null  int64
 19  reserved_room_type              119390 non-null  int64
 20  assigned_room_type              119390 non-null  object
 21  booking_changes                 119390 non-null  int64
 22  deposit_type                    119390 non-null  object
 23  agent                           119390 non-null  float64
 24  company                         119390 non-null  float64
 25  days_in_waiting_list            119390 non-null  int64
 26  customer_type                   119390 non-null  object
 27  adr                             119390 non-null  float64
 28  required_car_parking_spaces     119390 non-null  int64
 29  total_of_special_requests       119390 non-null  int64
 30  reservation_status              119390 non-null  object
 31  reservation_status_date         119390 non-null  int64
 32  city                            119390 non-null  int64
dtypes: float64(4), int64(25), object(4)
memory usage: 30.1+ MB

In [ ]:
df

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date,city
0,18,0,342,2024,5,30,27,0,0,2,...,9.0,40.0,0,Transient,0.00,0,0,Check-Out,43426,3
1,28,0,737,2024,0,17,28,0,0,2,...,9.0,40.0,0,Transient,0.00,0,0,Check-Out,24703,13
2,20,0,7,2024,11,37,10,0,1,1,...,9.0,40.0,0,Transient,75.00,0,0,Check-Out,52529,5
3,26,0,13,2024,1,33,14,0,1,1,...,304.0,40.0,0,Transient,75.00,0,0,Check-Out,47115,11
4,27,0,14,2024,11,37,14,0,2,2,...,240.0,40.0,0,Transient,98.00,0,1,Check-Out,53433,12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119385,14,0,23,2024,11,39,29,2,5,2,...,394.0,40.0,0,Transient,96.14,0,0,Check-Out,56458,14
119386,13,0,102,2024,9,46,16,2,5,3,...,9.0,40.0,0,Transient,225.43,0,2,Check-Out,66453,13
119387,12,0,34,2024,0,16,19,2,5,2,...,9.0,40.0,0,Transient,157.71,0,4,Check-Out,22740,12
119388,0,0,109,2024,10,40,5,2,5,2,...,89.0,40.0,0,Transient,104.40,0,0,Check-Out,57754,0
119389,2,0,205,2024,2,51,21,2,7,2,...,9.0,40.0,0,Transient,151.20,0,2,Check-Out,73686,2

In [ ]:
# 4 objects not able to view their columns in df.info(), but found on 'df'