In [ ]:
import pandas as pd
from scipy.stats import chi2_contingency

# Load your file
df = pd.read_csv('/content/credit_analysis.csv')
df.head()

,CustomerID,Age,Gender,Income,LoanAmount,LoanTerm,CreditScore,EmploymentStatus,MaritalStatus,NumberOfDependents,ExistingLoansCount,LoanPurpose,Defaulted
0,1,56,Male,105680,4040,6,808,Self-employed,Single,4,1,Home,1
1,2,69,Male,22050,43422,48,625,Unemployed,Single,0,3,Business,1
2,3,46,Male,129996,27160,48,656,Employed,Married,2,1,Home,0
3,4,32,Male,53933,18633,6,690,Unemployed,Married,4,2,Car,1
4,5,60,Female,44951,30344,48,384,Unemployed,Single,2,0,Education,1

In [ ]:
df['Gender'].value_counts()

Gender
Male      521
Female    479
Name: count, dtype: int64

In [ ]:
df['EmploymentStatus'].value_counts()

EmploymentStatus
Self-employed    357
Unemployed       336
Employed         307
Name: count, dtype: int64

In [ ]:
df['MaritalStatus'].value_counts()

MaritalStatus
Married     360
Single      331
Divorced    309
Name: count, dtype: int64

In [ ]:
df['Defaulted'].value_counts()

Defaulted
1    737
0    263
Name: count, dtype: int64

In [ ]:
df['LoanPurpose'].value_counts()

LoanPurpose
Home         229
Car          212
Business     191
Personal     189
Education    179
Name: count, dtype: int64

In [ ]:
df.isnull().sum()

CustomerID            0
Age                   0
Gender                0
Income                0
LoanAmount            0
LoanTerm              0
CreditScore           0
EmploymentStatus      0
MaritalStatus         0
NumberOfDependents    0
ExistingLoansCount    0
LoanPurpose           0
Defaulted             0
dtype: int64

Cross-tab (short for cross-tabulation) creates a table showing frequencies of two categorical variables side-by-side. It's the foundation for chi-square tests

In [ ]:
table = pd.crosstab(df['Gender'], df['Defaulted'])
print(table)

chi2, p, dof, expected = chi2_contingency(table)
alpha = 0.05
print(f'Chi2: {chi2:.2f}, p-value: {p:.4f}, Degrees of freedom: {dof}')
#if p < alpha:
    #print('Reject null: Gender associated with Defaulted.')
#else:
    #print('No significant association.')

Defaulted    0    1
Gender
Female     129  350
Male       134  387
Chi2: 0.13, p-value: 0.7168, Degrees of freedom: 1

In [ ]:
if p < alpha:
    print('Reject null: Gender associated with Defaulted.')
else:
    print('No significant association.')

No significant association.

In [ ]:
table = pd.crosstab(df['EmploymentStatus'], df['Defaulted'])
print(table)

chi2, p, dof, expected = chi2_contingency(table)
#print(f'p-value: {p:.4f}')
print(f'Chi2: {chi2:.2f}, p-value: {p:.4f}, Degrees of freedom: {dof}')
if p < alpha:
    print('Significant: Employment linked to default risk.')

Defaulted           0    1
EmploymentStatus
Employed          102  205
Self-employed     121  236
Unemployed         40  296
Chi2: 54.14, p-value: 0.0000, Degrees of freedom: 2
Significant: Employment linked to default risk.

In [ ]:
table = pd.crosstab(df['LoanPurpose'], df['Defaulted'])
chi2, p, dof, expected = chi2_contingency(table)
print(f'Chi2: {chi2:.2f}, p-value: {p:.4f}, Degrees of freedom: {dof}')
print(f'p-value for LoanPurpose vs Defaulted: {p:.4f}')

Chi2: 11.57, p-value: 0.0209, Degrees of freedom: 4
p-value for LoanPurpose vs Defaulted: 0.0209

In [ ]:
if p < alpha:
    print('Reject null: LoanPurpose associated with Defaulted.')
else:
    print('No significant association.')

Reject null: LoanPurpose associated with Defaulted.

In [ ]:
table = pd.crosstab(df['MaritalStatus'], df['Defaulted'])
chi2, p, dof, expected = chi2_contingency(table)
print(f'Chi2: {chi2:.2f}, p-value: {p:.4f}, Degrees of freedom: {dof}')
print(f'p-value for LoanPurpose vs Defaulted: {p:.4f}')

Chi2: 0.80, p-value: 0.6687, Degrees of freedom: 2
p-value for LoanPurpose vs Defaulted: 0.6687

In [ ]:
if p < alpha:
    print('Reject null: LoanPurpose associated with Defaulted.')
else:
    print('No significant association.')

No significant association.

In [ ]:
import pandas as pd
from statsmodels.formula.api import ols
df = pd.read_csv('/content/credit_analysis.csv')
df.columns

Index(['CustomerID', 'Age', 'Gender', 'Income', 'LoanAmount', 'LoanTerm',
       'CreditScore', 'EmploymentStatus', 'MaritalStatus',
       'NumberOfDependents', 'ExistingLoansCount', 'LoanPurpose', 'Defaulted'],
      dtype='object')

In [ ]:
from statsmodels.stats.anova import _get_covariance, anova_lm
formula = 'Age ~ C(Defaulted)'
model = ols(formula, df).fit()
aov_table = anova_lm(model)
print(aov_table)

                 df         sum_sq     mean_sq         F    PR(>F)
C(Defaulted)    1.0     155.228135  155.228135  0.554654  0.456598
Residual      998.0  279305.122865  279.864853       NaN       NaN

In [ ]:
from statsmodels.formula.api import ols
from statsmodels.stats.anova import anova_lm

formula = 'Income ~ C(Defaulted)'
model = ols(formula, df).fit()
aov_table = anova_lm(model)
print(aov_table)

                 df        sum_sq       mean_sq         F    PR(>F)
C(Defaulted)    1.0  1.257854e+09  1.257854e+09  0.868614  0.351565
Residual      998.0  1.445219e+12  1.448116e+09       NaN       NaN

In [ ]:
print(df.columns)

Index(['CustomerID', 'Age', 'Gender', 'Income', 'LoanAmount', 'LoanTerm',
       'CreditScore', 'EmploymentStatus', 'MaritalStatus',
       'NumberOfDependents', 'ExistingLoansCount', 'LoanPurpose', 'Defaulted'],
      dtype='object')

In [ ]:
formula = 'CreditScore ~ C(Defaulted)'
model = ols(formula, df).fit()
aov_table = anova_lm(model)
print(aov_table)

                 df        sum_sq       mean_sq           F        PR(>F)
C(Defaulted)    1.0  5.601007e+06  5.601007e+06  291.162636  1.763879e-57
Residual      998.0  1.919822e+07  1.923669e+04         NaN           NaN

In [ ]:
formula = 'Defaulted ~ LoanAmount + LoanTerm + NumberOfDependents + ExistingLoansCount'
model = ols(formula, df).fit()
aov_table = anova_lm(model)
print(aov_table)

                       df      sum_sq   mean_sq          F    PR(>F)
LoanAmount            1.0    3.288801  3.288801  17.493416  0.000031
LoanTerm              1.0    0.014135  0.014135   0.075186  0.783987
NumberOfDependents    1.0    0.314214  0.314214   1.671334  0.196380
ExistingLoansCount    1.0    3.151646  3.151646  16.763875  0.000046
Residual            995.0  187.062204  0.188002        NaN       NaN

In [ ]:
df.drop(['Income', 'LoanTerm', 'NumberOfDependents', 'Age','CustomerID','MaritalStatus','Gender'], axis=1, inplace=True)

In [ ]:
df.columns

Index(['LoanAmount', 'CreditScore', 'EmploymentStatus', 'ExistingLoansCount',
       'LoanPurpose', 'Defaulted'],
      dtype='object')

In [ ]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
df['EmploymentStatus'] = label_encoder.fit_transform(df['EmploymentStatus'])
df['LoanPurpose'] = label_encoder.fit_transform(df['LoanPurpose'])
df.head()

,LoanAmount,CreditScore,EmploymentStatus,ExistingLoansCount,LoanPurpose,Defaulted
0,4040,808,1,1,3,1
1,43422,625,2,3,0,1
2,27160,656,0,1,3,0
3,18633,690,2,2,1,1
4,30344,384,2,0,2,1

In [ ]:
x=df.drop('Defaulted',axis=1)
y=df['Defaulted']
x
#

,LoanAmount,CreditScore,EmploymentStatus,ExistingLoansCount,LoanPurpose
0,4040,808,1,1,3
1,43422,625,2,3,0
2,27160,656,0,1,3
3,18633,690,2,2,1
4,30344,384,2,0,2
...,...,...,...,...,...
995,31462,744,2,4,3
996,14615,808,2,4,0
997,45900,568,0,3,3
998,43946,714,2,0,3
999,8851,544,1,1,3

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
#

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
x_train_scaled=scaler.fit_transform(x_train)
x_test_scaled=scaler.transform(x_test)

In [ ]:
from sklearn.linear_model import LogisticRegression
model=LogisticRegression()
model.fit(x_train_scaled,y_train)
y_pred=model.predict(x_train_scaled)

In [ ]:
from sklearn.metrics import accuracy_score,classification_report
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

0.815
              precision    recall  f1-score   support

           0       0.70      0.46      0.55        50
           1       0.84      0.93      0.88       150

    accuracy                           0.81       200
   macro avg       0.77      0.70      0.72       200
weighted avg       0.80      0.81      0.80       200

In [ ]:
from sklearn.linear_model import LogisticRegression
model=LogisticRegression()
model.fit(x_test_scaled,y_test)
y_pred=model.predict(x_test_scaled)

In [ ]:
from sklearn.metrics import accuracy_score,classification_report
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

0.845
              precision    recall  f1-score   support

           0       0.79      0.52      0.63        50
           1       0.86      0.95      0.90       150

    accuracy                           0.84       200
   macro avg       0.82      0.74      0.76       200
weighted avg       0.84      0.84      0.83       200

In [ ]:
from sklearn.tree import DecisionTreeClassifier
model=DecisionTreeClassifier()
model.fit(x_train_scaled,y_train)
y_pred=model.predict(x_test_scaled)
#

In [ ]:
from sklearn.metrics import accuracy_score,classification_report
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))
#

0.725
              precision    recall  f1-score   support

           0       0.45      0.46      0.46        50
           1       0.82      0.81      0.82       150

    accuracy                           0.72       200
   macro avg       0.63      0.64      0.64       200
weighted avg       0.73      0.72      0.73       200

In [ ]:
from sklearn.tree import DecisionTreeClassifier
model=DecisionTreeClassifier()
model.fit(x_test_scaled,y_test)
y_pred=model.predict(x_test_scaled)

In [ ]:
from sklearn.metrics import accuracy_score,classification_report
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        50
           1       1.00      1.00      1.00       150

    accuracy                           1.00       200
   macro avg       1.00      1.00      1.00       200
weighted avg       1.00      1.00      1.00       200

In [ ]:
from sklearn.ensemble import RandomForestClassifier
model=RandomForestClassifier(n_estimators=500)
model.fit(x_train_scaled,y_train)
y_pred=model.predict(x_test_scaled)

In [ ]:
from sklearn.metrics import accuracy_score,classification_report
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))
#

0.78
              precision    recall  f1-score   support

           0       0.57      0.48      0.52        50
           1       0.84      0.88      0.86       150

    accuracy                           0.78       200
   macro avg       0.70      0.68      0.69       200
weighted avg       0.77      0.78      0.77       200

In [ ]:
from sklearn.ensemble import RandomForestClassifier
model=RandomForestClassifier()
model.fit(x_test_scaled,y_test)
y_pred=model.predict(x_test_scaled)

In [ ]:
from sklearn.metrics import accuracy_score,classification_report
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))
#

1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        50
           1       1.00      1.00      1.00       150

    accuracy                           1.00       200
   macro avg       1.00      1.00      1.00       200
weighted avg       1.00      1.00      1.00       200

In [ ]:
from sklearn.naive_bayes import GaussianNB
model=GaussianNB()
model.fit(x_train_scaled,y_train)
y_pred=model.predict(x_test_scaled)

In [ ]:
from sklearn.metrics import accuracy_score,classification_report
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

0.81
              precision    recall  f1-score   support

           0       0.69      0.44      0.54        50
           1       0.83      0.93      0.88       150

    accuracy                           0.81       200
   macro avg       0.76      0.69      0.71       200
weighted avg       0.80      0.81      0.79       200